# Generated by Django 4.2.6 on 2023-10-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mailactivated',
        ),
    ]
