# Generated by Django 4.2.6 on 2023-10-20 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_mailactivated_user_created_at'),
        ('account', '0003_user_auth_token_user_created_at'),
    ]

    operations = [
    ]
