# Generated by Django 4.2.6 on 2023-10-20 22:17

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_user_auth_token_alter_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(default='EG', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.URLField(null=True),
        ),
    ]
