# Generated by Django 4.2.6 on 2023-10-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_birthdate_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='account/images/%Y/%m/%d/%H/%M/%S/'),
        ),
    ]
