# Generated by Django 4.2.6 on 2023-10-19 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 10, 19, 19, 34, 52, 103569, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 10, 19, 19, 34, 52, 102569, tzinfo=datetime.timezone.utc)),
        ),
    ]
