# Generated by Django 4.2.6 on 2023-10-20 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_donation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 10, 20, 22, 17, 1, 526892, tzinfo=datetime.timezone.utc)),
        ),
    ]
