# Generated by Django 4.2.6 on 2023-10-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_donation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='total_target',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
