# Generated by Django 4.2.6 on 2023-10-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_project_photos_alter_project_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='photos',
        ),
        migrations.AddField(
            model_name='project',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/%Y/%m/%d/%H/%M/%S'),
        ),
    ]
