# Generated by Django 4.2.6 on 2023-10-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_alter_donation_project_alter_donation_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='total_target',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
