# Generated by Django 4.2.6 on 2023-10-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_remove_project_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
