# Generated by Django 4.2.6 on 2023-10-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0002_comment_created_at_report_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
