# Generated by Django 4.2.6 on 2023-10-24 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0026_alter_project_total_target'),
        ('Feedback', '0003_alter_review_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='statues',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='report',
            name='comment',
        ),
        migrations.AlterField(
            model_name='report',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
